config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

unless ENV['daemon']
  Avicus::Application.routes.draw do

    if Rails.env.development?
      mount GraphiQL::Rails::Engine, at: '/graphic-api', graphql_path: '/api'
    end

    if Avicus::Application.app_mode == 'api'
      post '', to: 'graphql#execute'
      root 'pages#home_api'
    else
      # Peek
      mount Peek::Railtie => '/peek'

      # Blazer
      mount Blazer::Engine, at: 'blazer'

      resources :livestream, :path => :live

      resources :appeals
      get 'appeal' => 'appeals#appeal'

      scope 'alerts' do
        get '' => 'alerts#index', :as => 'alerts'
        get ':id' => 'alerts#delete', :as => 'destroy_alert'
      end

      scope 'servers' do
        get '' => 'servers#index'
      end

      scope 'stats' do
        get '' => 'stats#index'
      end

      scope 'experience' do
        get '' => 'stats#experience'
      end

      scope 'play', :controller => 'play' do
        get '' => 'play#index'
        get 'server/:server_id' => 'play#server'
        get 'players' => 'play#players'
      end

      scope 'maps', :controller => 'maps' do
        get '' => 'maps#index'
        get 'map/:map' => 'maps#map'
        get 'map/:map/ratings/:version' => 'maps#ratings'
        get 'category/:cat' => 'maps#category'
      end

      scope 'sessions' do
        get 'new' => 'sessions#new', :as => 'new_session'
        post 'new' => 'sessions#create', :as => 'create_session'
        delete '' => 'sessions#destroy', :as => 'destroy_session'
      end

      scope 'messages' do
        get '' => 'messages#index', :as => 'messages'
        get 'to-search' => 'messages#search'
        get 'compose' => 'messages#compose', :as => 'compose_message'
        post 'compose' => 'messages#create', :as => 'create_message'
        get 'delete' => 'messages#delete', :as => 'delete_message'
      end

      # Pages
      get 'staff' => 'pages#staff'
      get 'confirm/:uuid' => 'pages#confirm'
      get 'development' => 'pages#development'
      get 'development/:repo' => 'pages#development'

      # Legacy
      get 'revisions' => redirect('/development')
      get 'revisions/:repo' => redirect('/development//%{repo}')
      get 'register' => redirect('/users/register')

      # Handy Redirects
      %w(xp prestige prestiges).each do |xp|
        get "#{xp}" => redirect('/experience')
      end
      # Competitve
      get 'streams' => redirect('/live')
      get 'scrimmages' => redirect('/scrims')
      # Official
      get 'stafflist' => redirect('/staff')
      %w(infractions bans warns kicks).each do |punish|
        get "#{punish}" => redirect('/punishments')
      end

      resources :punishments
      post 'punish' => 'punishments#punish', :as => :punish

      draw 'admin_routes'
      draw 'competitive_routes'
      draw 'forum_routes'
      draw 'session_routes'
      draw 'user_routes'

      scope ':user' do
        get '' => 'users#profile', :as => 'user'
      end

      root 'pages#home'
    end
    # Match Bad Routing
    match '*not_found', :to => 'application#render_404', :via => :all
  end
end

app/views/shared/404.haml
= content_for :title, '404 - Page Not Found!'

.banner{style: 'height: 220px'}
  %img{src: '/assets/defense.png'}
  .overlay
    %h1.pull-right{style: 'font-size: 80px;'}
      404
      %br
      %small{style: 'font-size: 20px'} The requested page could not be found.

app/views/shared/500.haml
= content_for :title, '500 - An error was encountered during the request.'

.banner{style: 'height: 220px'}
  %img{src: '/assets/defense.png'}
  .overlay
    .row
      %h1.pull-right{style: 'font-size: 80px;'}
        500
        %br
        %small{style: 'font-size: 20px'} An error was encountered during the request.
    .row
      %h3.pull-right
        Exception ID:
        %small{style: 'font-size: 20px'}= @id

- can_see_stacks = current_user.nil? ? false : current_user.has_permission?(:application_controllers, :view, :full_stacks, true)
- if Rails.env == 'development' || can_see_stacks
  %br
  .container-fluid
    %h2= @exception.message
    %h3 Params:
    %code= params
    %hr
    - @exception.backtrace.each do |t|
      %code= t
      %br
  %br

app/views/shared/_errors.haml
- if model.errors.any?
  .alert.alert-danger
    #error_explanation
      %h4 Errors:
      - model.errors.full_messages.each do |msg|
        \&bull; #{msg}
        %br

app/views/shared/_punishments.haml
- if punishments && punishments.size > 0
  .table-responsive
    %table.table.table-bordered.table-striped.table-no-sort.no-margin
      %thead
        %tr
          %th{:width => '5%'} #
          %th{:width => '13%'} Punished
          %th{:width => '13%'} Staff
          %th{:width => '7%'} Type
          %th{:width => '15%'} Reason
          %th{:width => '22%'} Date
          %th{:width => '12%'} Expires
          - if logged_in?
            %th{:width => '16%'} Actions
      %tbody
        - punishments.each do |p|
          - next if p.user == nil || !p.can_execute?(current_user, :view)
          - next if p.appealed? && !p.can_execute?(current_user, :view_appealed)
          %tr{:class => p.appealed? ? 'success' : ''}
            %td
              = link_to p.id, punishment_path(p)
            %td
              = link_avatar_to_user(p.user, 16) + ' ' + link_to_user(p.user)
            %td
              - if p.staff_id == 0 || p.staff.nil?
                Console
              - else
                =  link_avatar_to_user(p.staff, 16) + ' ' +link_to_user(p.staff)
            %td
              = p.type.gsub('_',' ').titleize
            -#{:style => 'word-break: break-all'} work on this again
            %td
              = p.reason
            %td
              = time_in_words p.date, true
            %td
              = (p.expires.presence) ? time_in_words(p.expires, true) : ''
            - if logged_in?
              %td
                .actions
                  - if p.can_execute?(current_user, :update)
                    = link_to 'Edit', edit_punishment_path(p), :class => 'btn btn-mini btn-info'
                  - if !p.appealed?
                    - if !Appeal.where(:punishment_id => p.id).empty? && Appeal.can_execute?(current_user, p, :view)
                      = link_to 'See Appeal', appeal_path(Appeal.where(:punishment_id => p.id).first), :class => 'btn btn-mini btn-warning'
                    - elsif current_user == p.user
                      = link_to 'Appeal', new_appeal_url + "?punishment_id=#{p.id}", :class => 'btn btn-mini btn-danger'
    %p
      - if punishments.respond_to?(:total_pages)
        = will_paginate punishments
- else
  No punishments found.

app/views/shared/_reports.haml
- if reports.size > 0
  %table.table.table-bordered.table-striped.table-no-sort
    %thead
      %tr
        %th{:width => '13%'} Reported
        %th{:width => '13%'} Reporter
        %th{:width => '15%'} Reason
        %th{:width => '15%'} Server
        %th{:width => '20%'} Date
    %tbody
      - reports.each do |r|
        - next unless r.can_execute?(current_user, :view)
        %tr
          %td= link_to_user(r.user)
          %td= r.creator_id == 0 ? 'Console' : link_to_user(r.creator)
          %td= truncate(r.reason.gsub(/&./, ''))
          %td= r.server
          %td= time_in_words r.created_at, true
  .text-center
    = will_paginate reports
- else
  %p.text-center No reports found.

app/views/shared/banned.haml
= content_for :title, 'Website Ban'
%section.section-dark.main-header
  .container-fluid
    .row-fluid
      .span12
        %h1 Website Ban Active
        %p Access to the website has been restricted under your account.

%section.section-padded
  .container-fluid
    .row-fluid
      .span12.text-center
        %p
          Reason:
          %b
            = @punishment.reason
        %hr
        %p
          - if @punishment.type == 'web_ban'
            A permanent website ban is active on your account.
          - else
            A temporary website ban which will expire on
            %b
              = time_in_words(@punishment.expires, true)
            = '(' + time_ago(@punishment.expires) + ' remaining)'
            is active on your account.
        %p
          If you believe this is an error or would like to dispute your ban, please visit the
          %a{:href => '/support'} support
          page.
        %p
          Be sure to revisit the rules if you before appealing.

app/views/shared/banned_tourney.haml
= content_for :title, 'Tournament Ban'
%section.section-dark.main-header
  .container-fluid
    .row-fluid
      .span12
        %h1 Tournament Ban Active
        %p Access to participate in tournaments has been restricted under your account.

%section.section-padded
  .container-fluid
    .row-fluid
      .span12.text-center
        %p
          Reason:
          %b
            = @punishment.reason
        %hr
        %p
          A tournament ban is active on your account.
        %p
          If you believe this is an error or would like to dispute your ban, please visit the
          %a{:href => '/support'} support
          page.
        %p
          Be sure to revisit the rules if you do before appealing.

app/views/shared/maint.haml
= content_for :title, 'Website Ban'
%section.section-dark.main-header
  .container-fluid
    .row-fluid
      .span12
        %h1 Forum Maintenance in Progress...
        %p Access to the forums is currently unavailable! Sorry about that!

%section.section-padded
  .container-fluid
    .row-fluid
      %blockquote
        %p
          Fearlessness is not the absence of fear. It's the mastery of fear. It's about getting up more times than we fall down.
        %small
          Arianna Huffington, editor-in-chef of The Huffington Post.
    %hr
    .row-fluid
      .span12.text-center
        %h3
          You can follow us on our
          %a{href: ''} Twitter 
          for the most up to date news and information about when the forums will return.

        %br
        %p
          %strong NOTE:
          You can still access other parts of the website!