config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

unless ENV['daemon']
  Avicus::Application.routes.draw do

    if Rails.env.development?
      mount GraphiQL::Rails::Engine, at: '/graphic-api', graphql_path: '/api'
    end

    if Avicus::Application.app_mode == 'api'
      post '', to: 'graphql#execute'
      root 'pages#home_api'
    else
      # Peek
      mount Peek::Railtie => '/peek'

      # Blazer
      mount Blazer::Engine, at: 'blazer'

      resources :livestream, :path => :live

      resources :appeals
      get 'appeal' => 'appeals#appeal'

      scope 'alerts' do
        get '' => 'alerts#index', :as => 'alerts'
        get ':id' => 'alerts#delete', :as => 'destroy_alert'
      end

      scope 'servers' do
        get '' => 'servers#index'
      end

      scope 'stats' do
        get '' => 'stats#index'
      end

      scope 'experience' do
        get '' => 'stats#experience'
      end

      scope 'play', :controller => 'play' do
        get '' => 'play#index'
        get 'server/:server_id' => 'play#server'
        get 'players' => 'play#players'
      end

      scope 'maps', :controller => 'maps' do
        get '' => 'maps#index'
        get 'map/:map' => 'maps#map'
        get 'map/:map/ratings/:version' => 'maps#ratings'
        get 'category/:cat' => 'maps#category'
      end

      scope 'sessions' do
        get 'new' => 'sessions#new', :as => 'new_session'
        post 'new' => 'sessions#create', :as => 'create_session'
        delete '' => 'sessions#destroy', :as => 'destroy_session'
      end

      scope 'messages' do
        get '' => 'messages#index', :as => 'messages'
        get 'to-search' => 'messages#search'
        get 'compose' => 'messages#compose', :as => 'compose_message'
        post 'compose' => 'messages#create', :as => 'create_message'
        get 'delete' => 'messages#delete', :as => 'delete_message'
      end

      # Pages
      get 'staff' => 'pages#staff'
      get 'confirm/:uuid' => 'pages#confirm'
      get 'development' => 'pages#development'
      get 'development/:repo' => 'pages#development'

      # Legacy
      get 'revisions' => redirect('/development')
      get 'revisions/:repo' => redirect('/development//%{repo}')
      get 'register' => redirect('/users/register')

      # Handy Redirects
      %w(xp prestige prestiges).each do |xp|
        get "#{xp}" => redirect('/experience')
      end
      # Competitve
      get 'streams' => redirect('/live')
      get 'scrimmages' => redirect('/scrims')
      # Official
      get 'stafflist' => redirect('/staff')
      %w(infractions bans warns kicks).each do |punish|
        get "#{punish}" => redirect('/punishments')
      end

      resources :punishments
      post 'punish' => 'punishments#punish', :as => :punish

      draw 'admin_routes'
      draw 'competitive_routes'
      draw 'forum_routes'
      draw 'session_routes'
      draw 'user_routes'

      scope ':user' do
        get '' => 'users#profile', :as => 'user'
      end

      root 'pages#home'
    end
    # Match Bad Routing
    match '*not_found', :to => 'application#render_404', :via => :all
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Permissions::Forums
  include Permissions::Editable

  belongs_to :forum
  has_many :discussions

  after_destroy :clean_up

  serialize :tags

  # Permissions start

  def self.permission_definition
    {
        :id_based => false,
        :global_options => {
            :text => 'Admin - Categories',
            options: [:true, :false],
        },
        :permissions_sets => [{
                                  :edit => [:name, :priority, :forum_id, :desc, :tags],
                                  :actions => [:create, :update, :destroy]
                              }]
    }
  end

  # Delete dependant classes which should no longer exist if this is deleted.
  def clean_up
    Discussion.where(category_id: self.id).each do |d|
      Reply.where(discussion_id: d.id).destroy_all
      Revision.where(discussion_id: d.id).destroy_all
      d.destroy
    end
  end

  def self.perm_fields
    self.permission_definition[:permissions_sets][0][:edit]
  end

  def can_mass_moderate?(user)
    user.has_permission?(:categories, self.id, :mass_moderate, true)
  end

  # Admin panel
  def admin_can_execute?(user, *action)
    action.flatten!
    return false if user.nil?

    return user.has_permission?(:categories, :actions, action, true)
  end

  # Permissions end
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  include Permissions::Editable
  include Permissions::Executable

  has_many :categories

  after_destroy :clean_up

  # Delete dependant classes which should no longer exist if this is deleted.
  def clean_up
    cats = Category.where(forum_id: self.id)
    cats.each do |c|
      Discussion.where(category_id: c.id).each do |d|
        Reply.where(discussion_id: d.id).destroy_all
        Revision.where(discussion_id: d.id).destroy_all
        d.destroy
      end
      c.destroy
    end
  end

  # Permissions start

  def self.permission_definition
    {
        :id_based => false,
        :global_options => {
            :text => 'Admin - Forums',
            options: [:true, :false],
        },
        :permissions_sets => [{
                                  :edit => [:name, :priority],
                                  :actions => [:create, :update, :destroy]
                              }]
    }
  end

  def self.perm_fields
    self.permission_definition[:permissions_sets][0][:edit]
  end

  # Permissions end
end

app/controllers/admin/forums_controller.rb
class Admin::ForumsController < Admin::IndexController
  before_action :set_forum, only: [:edit_forum, :update_forum, :destroy_forum]
  before_action :set_category, only: [:edit_category, :update_category, :destroy_category]
  before_action :perms_check


  def self.permission_definition

  end

  # GET /forums
  def index
    @forums = Forum.all.order('priority DESC')
    @categories = Category.all
  end

  # POST /forums
  def create_forum
    @forum = Forum.new(forum_params)
    redirect_if_fail(@forum.can_execute?(current_user, :create), admin_forums_url, :action); return if performed?

    # Edit all on creation
    @editable = Forum.perm_fields

    if @forum.save
      admin_log(:forums, current_user, :create_forum, @forum.name)
      redirect_to action: :index, notice: 'Forum was successfully created.'
    else
      render action: :index, notice: 'An error occured while creating the forum'
    end
  end

  def edit_forum
    redirect_if_fail(@forum.can_execute?(current_user, :update), admin_forums_url, :action); return if performed?

    @editable = editable_fields(@forum)
  end

  # PATCH/PUT /forums/1
  def update_forum
    redirect_if_fail(@forum.can_execute?(current_user, :update), admin_forums_url, :action); return if performed?

    if @forum.update(forum_params)
      redirect_to action: :index, notice: 'Forum was successfully updated.'
      admin_log(:forums, current_user, :update_forum, @forum.name)
    else
      render action: :edit_forum, notice: 'An error occured while updating the forum'
    end
  end

  # DELETE /forums/1
  def destroy_forum
    redirect_if_fail(@forum.can_execute?(current_user, :destroy), admin_forums_url, :action); return if performed?

    @forum.destroy
    admin_log(:forums, current_user, :destroy_forum, @forum.name)
    redirect_to admin_forums_url, notice: 'Forum was successfully destroyed.'
  end

  # POST /categories
  def create_category
    @category = Category.new(category_params)
    redirect_if_fail(@category.admin_can_execute?(current_user, :create), admin_forums_url, :action); return if performed?

    # Edit all on creation
    @editable = Category.perm_fields

    if @category.save
      redirect_to action: :index, notice: 'Forum was successfully created.'
      admin_log(:forums, current_user, :create_category, @category.name)
    else
      render action: :index, notice: 'An error occured while creating the category'
    end
  end

  def edit_category
    redirect_if_fail(@category.admin_can_execute?(current_user, :update), admin_forums_url, :action); return if performed?

    @forums = Forum.all
    @editable = editable_fields(@category)
  end

  # PATCH/PUT /categories/1
  def update_category
    redirect_if_fail(@category.admin_can_execute?(current_user, :update), admin_forums_url, :action); return if performed?

    if @category.update(category_params)
      redirect_to action: :index, notice: 'Category was successfully updated.'
      admin_log(:forums, current_user, :update_category, @category.name)
    else
      render action: :edit_category, notice: 'An error occured while updating the category'
    end
  end

  # DELETE /categories/1
  def destroy_category
    redirect_if_fail(@category.admin_can_execute?(current_user, :destroy), admin_forums_url, :action); return if performed?

    @category.destroy
    admin_log(:forums, current_user, :destroy_category, @category.name)
    redirect_to admin_forums_url, notice: 'Forum was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_forum
    @forum = Forum.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def perms_check
    redirect_if_fail(current_user.has_permission?('admin:index_controllers', :view, :forums, true), '/', :page)
  end

  # Only allow a trusted parameter "white list" through.
  def forum_params
    params.require(:forum).permit(:name, :priority)
  end

  def category_params
    params.require(:category).permit(:name, :priority, :tags, :desc, :forum_id)
  end
end

app/controllers/forums/categories_controller.rb
class Forums::CategoriesController < Forums::IndexController

  def show
    @category = Category.where(id: params[:id]).first

    redirect_if_fail(@category.can_execute?(current_user, :view), forums_path, 'You do not have permission to view this category.'); return if performed?

    @discussions = Discussion.where(category_id: @category.id)
    unless params[:tag].blank?
      revisions = Revision.select(:discussion_id).where(tag: params[:tag])
      ids = revisions.map { |r| r.discussion_id }
      @discussions = @discussions.where('id IN (?)', ids)
    end
    @discussions = @discussions.order('stickied DESC,updated_at DESC').paginate(:page => params[:page], :per_page => 25)
  end

  def mass_moderate
    @category = Category.where(id: params[:category_id]).first

    redirect_if_fail(@category.can_execute?(current_user, :view), forums_path, 'You do not have permission to view this category.'); return if performed?

    redirect_if_fail(@category.can_mass_moderate?(current_user), forums_path, :action); return if performed?

    success = false

    params[:act_on].each do |dis, val|
      discussion = Discussion.find_by_id(dis)
      next if discussion.nil?
      previous = discussion.revision
      revision = discussion.revision.dup
      revision.user = current_user
      locked = params[:locked].blank? ? revision.locked : params[:locked]
      archived = params[:archived].blank? ? revision.archived : params[:archived]

      if archived != revision.archived && discussion.can_execute?(current_user, discussion.user, :archive)
        revision.archived = archived
      end

      if locked != revision.locked && discussion.can_execute?(current_user, discussion.user, :lock)
        revision.locked = locked
      end

      discussion.archived = revision.archived

      if revision.save
        Discussion.record_timestamps = false
        discussion.save
        Discussion.record_timestamps = true

        previous.active = 0
        previous.save
        success = true
      else
        success = false
        redirect_to :back, error: 'Discussions were not updated'
      end
    end

    if success
      redirect_to category_path(@category), notice: 'Discussions were successfully updated'
      return
    end
  end


end

app/controllers/forums/index_controller.rb
class Forums::IndexController < ApplicationController

  before_action :global_vars

  def self.permission_definition

  end

  helper 'forums'

  def index
    handle_legacy

    exclude = Category.where(:exclude_from_recent => true).map(&:id).push(-1)
    viewable = ForumsHelper.viewable_categories(current_user)

    @discussions = Discussion.where('category_id NOT IN (?)', exclude)
    @discussions = @discussions.where('category_id IN (?)', viewable)
    @discussions = @discussions.select(:id, :user_id, :stickied, :archived, :category_id, :created_at, :updated_at, :uuid, :views)

    @discussions = @discussions.order('updated_at DESC').paginate(:page => params[:page], :per_page => 25)
  end

  def mark_all_read
    category_id = params[:category_id]
    discussion_id = params[:discussion_id]

    category = Category.find_by_id(category_id) unless category_id.nil?
    discussion = Discussion.find_by_id(discussion_id) unless discussion_id.nil?

    category = nil unless discussion.nil?

    redirect_to :back if category.nil? && !category_id.nil?; return if performed?
    redirect_to :back if discussion.nil? && !discussion_id.nil?; return if performed?

    notice = ''
    if !discussion.nil?
      discussion.mark_as_read! for: current_user
      discussion.replies.mark_as_read! :all, for: current_user
      notice = 'Marked all replies to this topic as read.'
    elsif category.nil?
      Discussion.mark_as_read! :all, for: current_user
      Reply.mark_as_read! :all, for: current_user
      notice = 'Marked all discussions as read.'
    else
      all = Discussion.where(category_id: category.id)
      all.each do |discussion|
        discussion.mark_as_read! for: current_user
        discussion.replies.mark_as_read! :all, for: current_user
      end
      notice = 'Marked all discussions in this topic as read.'
    end
    flash.now[:notice] = notice
    redirect_to :back
  end

  def my_subscriptions
    redirect_if_fail(logged_in?, forums_path, :login); return if performed?

    subs = [0] + current_user.subscriptions

    @discussions = Discussion.select(:id, :user_id, :stickied, :archived, :category_id, :created_at, :updated_at, :uuid, :views).where('id IN (?)', subs)
    @discussions = @discussions.order('updated_at DESC').paginate(:page => params[:page], :per_page => 25)
  end

  def my_discussions
    redirect_if_fail(logged_in?, forums_path, :login); return if performed?

    @discussions = Discussion.select(:id, :user_id, :stickied, :archived, :category_id, :created_at, :updated_at, :uuid, :views).where(:user_id => current_user.id)
    @discussions = @discussions.order('updated_at DESC').paginate(:page => params[:page], :per_page => 25)
  end

  def search
    @discussions = Discussion.select(:id, :user_id, :stickied, :archived, :category_id, :created_at, :updated_at, :uuid, :views)
    viewable = ForumsHelper.viewable_categories(current_user)
    @discussions = @discussions.where('category_id IN (?)', viewable)
    @discussions = @discussions.where(category_id: params[:category_id]) unless params[:category_id].nil?
    @discussions = @discussions.where(:user_id => current_user.id) unless params[:disc].nil?
    @discussions = @discussions.where('id IN (?)', current_user.subscriptions) unless params[:subs].nil?

    unless params[:author].blank?
      author = User.select(:id).find_by_username(params[:author])
      if author
        @discussions = @discussions.where(:user_id => author.id)
      else
        @discussions = @discussions.where(:user_id => 0)
      end
    end

    unless params[:query].blank?
      if params[:query].size >= 3
        revisions = Revision.select(:discussion_id).where(:active => 1).where('MATCH (title,body) AGAINST (? IN BOOLEAN MODE)', params[:query])
        ids = revisions.map { |r| r.discussion_id }

        @discussions = @discussions.where('id IN (?)', ids)
      else
        flash[:error] = 'Search must be at least 3 characters.'
      end
    end

    @discussions = @discussions.order('updated_at DESC').paginate(:page => params[:page], :per_page => 25)
    render :index
  end

  private

  def handle_legacy
    redirect_to Category.find_by_id(params[:topic_id]) if params[:topic_id].present?
  end

  def global_vars
    @categories = Category.select(:id, :name, :desc).all.order('priority DESC')
    @forums = Forum.select(:id, :name).all
  end

end

app/helpers/forums_helper.rb
module ForumsHelper
  # Get a link to a certain reply inside of a discussion.
  def find_reply_path(reply)
    discussion_path(reply.discussion, :reply => reply.id)
  end

  # Get an array of forums and categories for use in a dropdown menu.
  def self.options_for_select(user)
    all = []

    Forum.all.each do |cat|
      list = cat.categories

      viewable = ForumsHelper.filter_categories(user, list)

      next if viewable.empty?

      all.push(["--- #{cat.name} ---", -1, :disabled => 'disabled'])

      viewable.each do |topic|
        all.push([topic.name, topic.id])
      end
    end

    all
  end

  # Filter an array of categories to only ones that a user can view.
  def self.filter_categories(user, *categories)
    categories.flatten.delete_if { |c| !c.can_view?(user) }
  end

  # Get an array of categories that a user can view.
  def self.viewable_categories(user)
    categories = Category.all
    viewable = []
    categories.each do |category|
      view = category.can_view?(user)
      viewable << category if view
    end
    viewable
  end
end

app/views/forums/categories/show.haml
= content_for :title, @category.name

%section.section-dark.main-header
  .container-fluid
    .row-fluid
      .span6
        %h1.topic-title
          = @category.name
        %p
          = @category.desc
      .span6.pull-right
        - if logged_in?
          = render 'forums/shared/read_sub', :sub => false

          - if @category.can_execute?(current_user, :create)
            = form_tag(new_discussion_path, {:method => 'get', :class => 'pull-right form-inline', :style => 'padding-top: 10px'}) do
              &nbsp;
              = hidden_field_tag 'cat_id', @category.id
              = submit_tag 'New Discussion', :class => 'btn btn-success'

        %a.btn.btn-warning.pull-right.open-search{:style => 'margin-top: 10px'}
          Search
          &nbsp;
          %i.fa.fa-caret-down

        - if @category.can_mass_moderate?(current_user)
          %a.btn.btn-info.pull-right.open-moderation{:style => 'margin-top: 10px; margin-right: 5px'}
            Mass Moderate
            &nbsp;
            %i.fa.fa-caret-down

:javascript
  $(".open-search").click(function () {
    $("#search").slideToggle(200);
    $("#author").focus();
  })

  $(".open-moderation").click(function () {
    $("#moderation").slideToggle(200);
  })

%section.section.section-padded
  .container-fluid
    .row-fluid
      .span9.pull-right
        = render 'forums/shared/search'

        .breadcrumb
          %li
            = @category.forum.name
          %span.divider /
          %li.active
            = @category.name
        = form_tag category_mass_moderate_path(@category), :method => 'post', :class => 'form-inline' do
          - if @category.can_mass_moderate?(current_user)
            #moderation{:style => 'display: none'}
              .row-fluid
                .span3
                  = button_tag 'Lock', class: 'btn btn-info', name: 'locked', value: 1
                .span3
                  = button_tag 'Unlock', class: 'btn btn-info', name: 'locked', value: 0
                .span3
                  = button_tag 'Archive', class: 'btn btn-info', name: 'archived', value: 1
                .span3
                  = button_tag 'Unarchive', class: 'btn btn-info', name: 'archived', value: 0

          .table-responsive
            %table.table.table-striped
              %thead
                %tr
                  - if @category.can_mass_moderate?(current_user)
                    %th{:style => 'width: 30px;'} Moderate
                  - if logged_in?
                    %th{:style => 'width: 20px;'}
                  %th Title
                  %th{:style => 'width: 100px;'} Activity
                  %th{:style => 'width: 205px; text-align: right'} Latest Post
              %tbody
                - @discussions.each do |discussion|
                  - if discussion == nil
                    - next
                  - if !discussion.can_execute_state?(current_user, :view)
                    - next

                  %tr
                    - if @category.can_mass_moderate?(current_user)
                      %td= check_box_tag "act_on[#{discussion.id}]"
                    - if logged_in?
                      %td
                        - unread = discussion.get_unread(current_user)
                        - if unread.size > 0
                          %a.label.label-warning.pull-right{:href => unread.first.link, :style => 'margin-top: 50%', :rel => 'tooltip', :title => "#{unread.size} unread posts"}
                            = unread.size
                    %td
                      = link_to discussion.title, discussion, :style => discussion.sticky? ? 'font-weight: bold' : ''
                      &nbsp;
                      %small{:style => 'font-size: 12px'}
                        - if discussion.sticky?
                          %i.fa.fa-star{:title => 'Stickied'} &nbsp;
                        - if discussion.archived?
                          %i.fa.fa-times{:title => 'Archived'} &nbsp;
                        - if discussion.locked?
                          %i.fa.fa-lock{:title => 'Locked'}
                      %br
                      %small.post-extras
                        %i.fa.fa-pencil
                        = link_to_user(discussion.user)
                        %i.fa.fa-clock-o
                        %a{:href => discussion_path(discussion), :rel => 'tooltip', :title => time_in_words(discussion.created_at, true)}
                          = time_ago discussion.created_at
                          ago
                        %i.fa.fa-folder-open
                        %a{:href => discussion.category_url}
                          = discussion.category.name
                        - if discussion.revision.tag.presence
                          %i.fa.fa-tag
                          %a{:href => "/forums/categories/#{discussion.category.id}?tag=#{discussion.revision.tag}"}
                            = discussion.revision.tag
                    %td
                      %b
                        = discussion.public_replies(current_user).size
                      = 'reply'.pluralize(discussion.public_replies(current_user).size)
                      %br
                      %small
                        %b
                          = discussion.views
                        = 'view'.pluralize(discussion.views)
                    %td
                      - latest = discussion.public_replies(current_user).last
                      - if discussion.public_replies(current_user).size > 0 && !latest.nil? && !latest.user.nil?
                        %div{:style => 'position:realtive; text-align: right'}
                          .pull-right{:style => 'position:relative; margin-left: 5px; margin-top: 4px'}
                            = link_to user_path(latest.user) do
                              %img.img-rounded{:src => latest.user.avatar(37)}
                          = link_to_user(latest.user)
                          .post-extras
                            %a{:href => find_reply_path(latest), :rel => 'tooltip', :title => time_in_words(latest.created_at, true)}
                              = time_ago latest.created_at
                              ago
                      - else
                        %div{:style => 'position:realtive; text-align: right'}
                          .pull-right{:style => 'position:relative; margin-left: 5px; margin-top: 4px'}
                            = link_to user_path(discussion.user) do
                              %img.img-rounded{:src => discussion.user.avatar(37)}
                          = link_to_user(discussion.user)
                          .post-extras
                            %a{:href => discussion_path(discussion), :rel => 'tooltip', :title => time_in_words(discussion.created_at, true)}
                              = time_ago discussion.created_at
                              ago
        - if @discussions.size == 0
          %p.text-center There are no discussions to display.
        = will_paginate @discussions

      .span3.pull-left
        = render 'forums/shared/navigation', :forums => @forums, :categories => @categories, :active => @category.id

:css
  td {
    line-height: 21px !important;
  }

:javascript
  $('.topic-title').each(function() {
    $(this).html($('.sidebar .active a .title').html());
  });